services:
  backend:
    build: ./backend
    command: ./entrypoint.sh rails s -b 0.0.0.0
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development

  frontend:
    working_dir: /app
    image: node:18
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
